[package]
name = "identity"
version = "0.4.1"
authors = ["IOTA Stiftung"]
documentation = "https://wiki.iota.org/identity.rs/introduction"
edition = "2018"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "identity", "did"]
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
description = "Tools for working with Self-sovereign Identity."

[dependencies]
identity-account = { version = "=0.4.1", path = "../identity-account", optional = true }
identity-comm = { version = "=0.4.1", path = "../identity-comm", optional = true }
identity-core = { version = "=0.4.1", path = "../identity-core" }
identity-credential = { version = "=0.4.1", path = "../identity-credential" }
identity-did = { version = "=0.4.1", path = "../identity-did" }
identity-iota = { version = "=0.4.1", path = "../identity-iota", default-features = false }

[dev-dependencies]
criterion = { version = "0.3" }
tokio = { version = "1.5", features = ["full"] }

[[bench]]
name = "benchmark"
harness = false

[features]
default = ["async"]

# Enables async runtime support (Tokio)
async = ["identity-iota/async"]

# Enables Web Assembly support
wasm = ["identity-iota/wasm", "identity-comm/wasm"]

# Enables support for secure storage of DID Documents
account = ["identity-account"]

# Enables support for DID Communication
comm = ["identity-comm"]

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps --workspace --open
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
