[package]
name = "identity-derive"
version = "0.4.1"
authors = ["IOTA Stiftung"]
edition = "2018"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "identity"]
license = "Apache-2.0"
readme = "../../README.md"
repository = "https://github.com/iotaledger/identity.rs"
description = "Derive `Diff` support for the identity-rs library."

[lib]
name = "identity_derive"
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0" }
quote = { version = "1.0" }
serde = { version = "1.0" }
syn = { version = "1.0", features = ["extra-traits", "parsing", "derive"] }
