[package]
name = "identity-wasm"
version = "0.4.0"
authors = ["IOTA Stiftung"]
edition = "2018"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "identity", "wasm"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/iotaledger/identity.rs"
resolver = "2"
description = "Web Assembly bindings for the identity-rs crate."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = { version = "0.1" }
futures = { version = "0.3" }
js-sys = { version = "0.3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = { version = "0.4", default-features = false }

[dependencies.identity]
version = "=0.4.1"
path = "../../identity"
default-features = false
features = ["comm", "wasm"]

[dev-dependencies]
wasm-bindgen-test = { version = "0.3" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
chrono = { version = "0.4", features = ["wasmbind"] }
getrandom = { version = "0.2", features = ["js"] }
parking_lot = { version = "0.11.2", features = ["wasm-bindgen"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = true

[profile.release]
opt-level = 's'
lto = true
